//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.ChiTietDonHang = new HashSet<ChiTietDonHang>();
        }
    
        public int MaSach { get; set; }
        public string TenSach { get; set; }
        public Nullable<int> MaTacGia { get; set; }
        public Nullable<int> MaNXB { get; set; }
        public Nullable<int> MaTL { get; set; }
        public decimal GiaBan { get; set; }
        public Nullable<decimal> PhanTramKM { get; set; }
        public Nullable<decimal> GiaKM { get; set; }
        public Nullable<int> NamXuatBan { get; set; }
        public int Soluongton { get; set; }
        public string AnhBia { get; set; }
        public Nullable<int> SoTrang { get; set; }
        public string MoTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
        public virtual NhaXuatBan NhaXuatBan { get; set; }
        public virtual TacGia TacGia { get; set; }
        public virtual TheLoai TheLoai { get; set; }
    }
}
